### ISSUE TITLE
HCF Upgrade

### ISSUE THREAD

**Issue by kj3moraes** [yde773786/Android-Studio-Projects#1]
Went over your HCF code briefly. It runs in _O(n)_ time which can be a bit troublesome for large 'n'. As a suggestion, you can replace it by two algorithms that run in _O( √n)_ and _O((log n)^3)_ respectively. Both are in the file attached. 
[HCFUPGRADE.txt](https://github.com/yde773786/3X3-Matrix-Inverse/files/4740757/HCFUPGRADE.txt)

**Comment by yde773786** [comment]
Updated. Thank you.
